In [5]:
import numpy as np
a = np.array([1,2])
b = np.array([4,5])
c = np.matrix([[1,2],[3,4]])
d = np.matrix([[5,6],[7,8]])

print("\nC:", type(c))
print(c)
print("\nD:", type(d))
print(d)
print("\nOperation on two ndarray objects (Elementwise):")
print(a * b)
print("\nOperation on two matrix objects (Matrix multiplication):")
print(c * d)


C: <class 'numpy.matrix'>
[[1 2]
 [3 4]]

D: <class 'numpy.matrix'>
[[5 6]
 [7 8]]

Operation on two ndarray objects (Elementwise):
[ 4 10]

Operation on two matrix objects (Matrix multiplication):
[[19 22]
 [43 50]]


In [8]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
print("a=",a)
print("\n with np.transpose(a) function")
print(np.transpose(a))

print("\n with ordinary transpose")
print(a.transpose())
print("\n with a.T attribute")
print(a.T)

a= [[1 2]
 [3 4]
 [5 6]]

 with np.transpose(a) function
[[1 3 5]
 [2 4 6]]

 with ordinary transpose
[[1 3 5]
 [2 4 6]]

 with a.T attribute
[[1 3 5]
 [2 4 6]]


In [11]:
#trace
a=np.array([
            [2,2,1],
            [1,3,1],
            [1,2,2]
            ])
print(a)
print("\nDiagonal elements are:")
sum=0
for i in range(len(a)):
      print(a[i][i])
      sum+=a[i][i]
print(f"\ntrace of a matrix:\n{sum}")

[[2 2 1]
 [1 3 1]
 [1 2 2]]

Diagonal elements are:
2
3
2

trace of a matrix:
7


In [15]:
import numpy as np
a=np.arange(1,10)
a.shape=(3,3)
print("a=",a)
print("Rank of Matrix is ",np.linalg.matrix_rank(a))

a= [[1 2 3]
 [4 5 6]
 [7 8 9]]
Rank of Matrix is  2


In [24]:
import numpy as np

a = np.array([
    [2, 2, 1],
    [1, 3, 1],
    [1, 2, 2]
])

#using function
det=np.linalg.det(a)
print(det)
#inverse
inv=np.linalg.inv(a)
print("inverse: ",inv)

4.999999999999999
inverse:  [[ 0.8 -0.4 -0.2]
 [-0.2  0.6 -0.2]
 [-0.2 -0.4  0.8]]


In [25]:
import numpy as np

a = np.array([
    [2,8],[1,4]
])
inv=np.linalg.inv(a)
print("inverse: ",inv)

LinAlgError: Singular matrix

In [26]:
#Eigen value
import numpy as np

a = np.array([
    [2, 2, 1],
    [1, 3, 1],
    [1, 2, 2]
])
w,v=np.linalg.eig(a)
print("Eigen value: ",w)
print("Eigen vector: ",v)

Eigen value:  [5. 1. 1.]
Eigen vector:  [[-0.57735027 -0.90453403  0.82529864]
 [-0.57735027  0.30151134 -0.52125218]
 [-0.57735027  0.30151134  0.21720572]]


In [41]:
import pandas as pd

data = pd.read_csv('/content/1995.csv')
data.info()
print(data.shape)
data.head(20)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Years    20 non-null     int64 
 1   Product  20 non-null     object
 2   Price    20 non-null     int64 
dtypes: int64(2), object(1)
memory usage: 612.0+ bytes
(20, 3)


Years    Product  Price
0    1995  Fast Food    200
1    1995      Sweet    150
2    1995  Fast Food    100
3    1995  Fast Food    250
4    1995  Fast Food    260
5    1995      Sweet    230
6    1995      Sweet    210
7    1995  Fast Food    120
8    1995      Sweet    150
9    1995  Fast Food    160
10   1995  Fast Food    140
11   1995      Sweet    180
12   1995  Fast Food    190
13   1995      Sweet    130
14   1995  Fast Food    123
15   1995      Sweet    210
16   1995      Sweet    250
17   1995  Fast Food    120
18   1995      Sweet    159
19   1995  Fast Food    160

In [50]:
import pandas as pd
data = pd.read_csv('/content/1995.csv',delimiter=',')
print(data)

    Years    Product  Price
0    1995  Fast Food    200
1    1995      Sweet    150
2    1995  Fast Food    100
3    1995  Fast Food    250
4    1995  Fast Food    260
5    1995      Sweet    230
6    1995      Sweet    210
7    1995  Fast Food    120
8    1995      Sweet    150
9    1995  Fast Food    160
10   1995  Fast Food    140
11   1995      Sweet    180
12   1995  Fast Food    190
13   1995      Sweet    130
14   1995  Fast Food    123
15   1995      Sweet    210
16   1995      Sweet    250
17   1995  Fast Food    120
18   1995      Sweet    159
19   1995  Fast Food    160


In [60]:
import pandas as pd
data=pd.read_csv('/content/1995.csv',skiprows=4)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   1995       16 non-null     int64 
 1   Fast Food  16 non-null     object
 2   250        16 non-null     int64 
dtypes: int64(2), object(1)
memory usage: 516.0+ bytes


In [73]:
import glob
file_list = glob.glob('/content/sample_data/files/years/*.csv')

for file in file_list:
  print(file)

all_data = pd.DataFrame()

for file in file_list:
  df = pd.read_csv(file)
  all_data = pd.concat([all_data, df],ignore_index=True)

print(all_data)
type(all_data)
all_data.head(20)

/content/sample_data/files/years/1995.csv
/content/sample_data/files/years/1998.csv
/content/sample_data/files/years/1996.csv
/content/sample_data/files/years/1997.csv
    Years    Product  Price
0    1995  Fast Food    200
1    1995      Sweet    150
2    1995  Fast Food    100
3    1995  Fast Food    250
4    1995  Fast Food    260
..    ...        ...    ...
75   1997      Sweet    210
76   1997      Sweet    250
77   1997  Fast Food    120
78   1997      Sweet    159
79   1997  Fast Food    160

[80 rows x 3 columns]


Years    Product  Price
0    1995  Fast Food    200
1    1995      Sweet    150
2    1995  Fast Food    100
3    1995  Fast Food    250
4    1995  Fast Food    260
5    1995      Sweet    230
6    1995      Sweet    210
7    1995  Fast Food    120
8    1995      Sweet    150
9    1995  Fast Food    160
10   1995  Fast Food    140
11   1995      Sweet    180
12   1995  Fast Food    190
13   1995      Sweet    130
14   1995  Fast Food    123
15   1995      Sweet    210
16   1995      Sweet    250
17   1995  Fast Food    120
18   1995      Sweet    159
19   1995  Fast Food    160

In [74]:
all_data.to_csv('all_data.csv',index=False)

In [75]:
x= pd.read_csv('/content/all_data.csv',delimiter=',')
print(x)
x.head(20)

    Years    Product  Price
0    1995  Fast Food    200
1    1995      Sweet    150
2    1995  Fast Food    100
3    1995  Fast Food    250
4    1995  Fast Food    260
..    ...        ...    ...
75   1997      Sweet    210
76   1997      Sweet    250
77   1997  Fast Food    120
78   1997      Sweet    159
79   1997  Fast Food    160

[80 rows x 3 columns]


Years    Product  Price
0    1995  Fast Food    200
1    1995      Sweet    150
2    1995  Fast Food    100
3    1995  Fast Food    250
4    1995  Fast Food    260
5    1995      Sweet    230
6    1995      Sweet    210
7    1995  Fast Food    120
8    1995      Sweet    150
9    1995  Fast Food    160
10   1995  Fast Food    140
11   1995      Sweet    180
12   1995  Fast Food    190
13   1995      Sweet    130
14   1995  Fast Food    123
15   1995      Sweet    210
16   1995      Sweet    250
17   1995  Fast Food    120
18   1995      Sweet    159
19   1995  Fast Food    160